coverage:
  status:
    project:
      backend:
        target: 90%
        flags:
          - backend
          - tests

flags:
  backend:
    paths:
      - social_app/userapp/

  tests:
    path:
      - social_app/tests/
