coverage:
  status:
    project:
      default:
        # basic
        target: 100%
        threshold: 0%
        base: auto 
        flags: 
          - social_app
        paths: 
          - "social_app"
