coverage:
  status:
    project:
      default: false
        tests:
          target: 100%
          threshold: 0%
          path: "social_app/tests"
        app:
          target: 100%
          threshold: 0%
          path: "social_app/userapp
