version: 2.1
orbs:
  codecov: codecov/codecov@3
  python: circleci/python@2.0.3
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: pytest
          command: pip install pytest
      - run: python -m pytest --junitxml=test-reports/test-results.xml --cov=./ --cov-report=xml --cov-report=html
      - codecov/upload:
          file: htmlcov
    


workflows:
  sample:
    jobs:
      - build-and-test
