version: 2.1
orbs:
  codecov: codecov/codecov@3
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: install pytest
          command: pip install pytest
      - run:
          name: run tests
          command: pytest --cov
      - codecov/upload


workflows:
  sample:
    jobs:
      - build-and-test
