version: 2.1
orbs:
  codecov: codecov/codecov@3
  python: circleci/python@2.0.3
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: run tests
          command: pytest
      - run: coverage report
      - run: coverage html

      - codecov/upload:


workflows:
  sample:
    jobs:
      - build-and-test
