version: 2.1

orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
          pytest
          coverage run -m pytest
          coverage html


workflows:
  sample:
    jobs:
      - build-and-test