version: 2.1

orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: install pytest
          command: pip install pytest
      - run:
          name: Setup testing environment
          command: |
            pip install '.[test]' --user
            echo $HOME
      - run:
          name: Run Tests
          command: |
            $HOME/.local/bin/coverage run -m pytest
            $HOME/.local/bin/coverage report
            $HOME/.local/bin/coverage html  # open htmlcov/index.html in a browser
      - store_artifacts:
          path: htmlcov


workflows:
  sample:
    jobs:
      - build-and-test
