version: 2.1

orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: install pytest
          command: pip install pytest
      - run:
          name: run tests
          command: pytest
      - run: mkdir test-reports
      - run: coverage report
      - run: coverage html
      - store_test_results:
         path: test-reports
      - store_artifacts:
         path: htmlcov


workflows:
  sample:
    jobs:
      - build-and-test
