name: workflow

on:
  push:
    paths:
      - 'social_app/**'

jobs:
  build:
    runs-on: macos-latest
    name: Test flask app
    defaults:
      run:
        working-directory: ./social_app
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: pytest --cov .
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        flags: backend
